src/components/score/score.tsx, src/pages/match/index.tsx, src/server/api/match-maker.ts, src/server/service/achievements.ts, src/server/service/agent.ts, src/server/service/match.ts, src/types/match.ts
This PR introduces an achievements check to the calculating points function. 
#142 
- [BE] Created function to check gets an achievement
- [BE] Added Record to define all the achievements
- [FE] Show the valid achievements in score section
=> Feat: achievements first implementation

src/server/service/agent.ts, src/server/service/match.ts
* Fix filter to properly exclude past agent inputs
* Add some TODOs for agent logic
=> fix(past inputs filter)

LICENSE, NOTICE
* Add LICENSE file
* Add NOTICE file with copyright
=> docs: apache2 license

src/server/api/match-maker.ts, src/server/api/routers/user.ts, src/server/db/index.ts, src/server/db/rank.ts, src/server/db/schema.ts, src/server/service/index.ts, src/server/service/leaderboard.ts, src/server/service/match.ts
This PR introduces the calculation of the ranks in a database table.
- SQL command to read user scores, calculate their position on the leaderboard and store it in the database
- Function that wraps around the SQL command
- Triggering score calculation on match end, score merge and user verification
=> feat: calculate ranks table

src/pages/login/index.tsx
This PR is a fix for triggering the Leo wallet from the main menu.
#160 
- [FE] Replaced function
=> bug(authentication): Bug trigger Leo wallet

deployment/local/deployment.yaml, deployment/staging/deployment.yaml, deployment/staging/secrets.template.yaml
Defined Aleo env variables in kustomize deployment configuration.
=> fix(staging): define aleo envs in kustomize

src/components/results/results.tsx, src/server/api/match-maker.ts, src/server/service/match.ts, src/service/bb-wallet.ts
This PR fixes wallet signature flow.
=> fix: return signature after sign

src/assets/text/index.ts, src/assets/text/support.ts, src/components/input-field/input-field.tsx, src/components/input-field/styles.ts, src/components/select-field/index.ts, src/components/select-field/select-field.tsx, src/components/select-field/styles.ts, src/constants/support.ts, src/pages/support.tsx, src/styles/pages/support.ts
closes #212 
related work: #209
=> feat(support page): Implement support page

src/components/score/score.tsx, src/server/service/match.ts
#211 changed a fn name without updating the imports, thus breaking the build, this fixes it
=> fix(broken-build): wrong case in import

.pnp.cjs, src/components/players/player-others/players-others.tsx, src/components/players/player-proofs/player-proofs.tsx, src/utils/characters.tsx, yarn.lock
This PR fixes an issue where `PlayerProofs` component would render an error view instead of an empty one.
=> fix: end of match error view

src/components/players/player-others/players-others.tsx
Disabling vote button if no bots have been selected by the player
=> fix: disable vote button if no bots selected

src/components/input-field/styles.ts, src/components/messages/message.tsx, src/components/messages/styles.ts, src/components/timer/styles.ts, src/components/timer/timer.tsx, src/styles/globals.css, src/utils/characters.tsx
=> Fix: Styling updates to Chat stage

src/components/chat/chat.tsx, src/components/chat/styles.ts
Chat prompt width is now proportional to chat box width.
=> fix: chat prompt width

src/server/service/agent.ts
=> fix(agent): update prompt template and unwanted characters filter

src/components/tables/components/row-create-username/row-create-username.tsx, src/utils/username.ts
This PR fixes the the invalid creation of usernames. 
closes #302 
- [FE] Replace . _ / to a -
- [FE] Make sure the username is smaller then 12 characters
=> bug(username): invalid username generation fix 

src/server/service/agent.ts
* Add 1/2 chances for the agent to reply to new messages in the chat.
=> feat(agent): add random reply trigger to agent

src/server/api/match-maker.ts
* Add min amount of bots to be 1
=> fix(matchmaker): add min amount of bots

src/components/chat/chat.tsx, src/components/error-view/error-view.tsx, src/components/input-field/text-input-field.tsx, src/components/navbar/navbar.tsx, src/components/players/player-others/players-others.tsx, src/components/primary-button/primary-button.tsx, src/components/results/results.tsx, src/components/tables/components/row-create-username/row-create-username.tsx, src/pages/player-profile.tsx, src/pages/support.tsx
- Removed primary button prop declaration causing error on primary button
- added sound externally to all primary button calls
=> fix: primary button error

src/components/lobby-character-loader/lobby-character-loader.tsx, src/constants/main.ts, src/pages/index.tsx, src/pages/lobby.tsx
This PR introduces music to the home page and match making screen
- added music to Home Page and Match Making Screen
- added a match ready flag to set all the characters ON
=> feat: home lobby music

src/assets/text/general.ts
Change name of anonymous user to anon
#329 
- [FE] Change constant
=> bug(usename): change name anonymous user 

src/server/service/agent.ts
* Add ranges to waiting time
* Update parameters for response generation
* Update system prompt
=> feat(agent): upgrade response logic

src/components/bot-buster-logo/botbuster-logo-animation.tsx, src/components/bot-buster-logo/styles.ts, src/components/chat/chat.tsx, src/components/chat/styles.ts, src/components/host-chat-prompt/host-chat-prompt.tsx, src/components/match-layout/match-layout.tsx, src/components/messages/styles.ts, src/components/players/player-others/players-others.tsx, src/components/timer/timer.tsx, src/components/transitions/styles.ts, src/components/transitions/transitions.tsx, src/constants/main.ts, src/pages/index.tsx, src/pages/lobby.tsx, src/server/service/match.ts, src/styles/pages/homepage.ts
This PR introduces music to the chat and voting stage.
- Added music to be in sync with the match timer
- Added 30 seconds left song including outro song when theres 2 seconds remaining
=> feat: Added Match Music

src/server/service/agent.ts
* Increase low boundary for reply delay
=> fix(agent): increase waiting time min value

src/components/character-avatar/character-avatar.tsx, src/utils/characters.tsx
- added a random speed for each character to randomize blinking
=> feat: characters now blink randomly

src/server/service/agent.ts, src/server/service/match.ts
Upgrade agent response waiting time based on message length and random ranges:
* Add inference time calculation
* Calculate waiting time based on inference time & generated response length
=> fix(agent): response waiting time

src/server/service/agent.ts
* Add filter for gender symbols:  ♂ or ♀
=> fix(agent): upgrade message RegEx filter

src/server/service/agent/agent.ts, src/server/service/agent/index.ts, src/server/service/agent/personality-matrix.ts, src/server/service/index.ts, src/types/agent.ts
* Generate random personality traits on match start
* Add personality matrix based on the "big five" traits
* Describe personality based on traits (openness, conscientiousness, extraversion, agreeableness, neuroticism)
=> feat(agent): personality matrix

src/server/api/match-maker.ts
* Decouple `makeMatch` interval from `storeScoresAndMatches`
=> fix(matchmaking): make match interval

src/server/api/routers/match.ts, src/server/service/match.ts, src/types/match.ts
* Add BE "player is typing" event subscription and handler
=> feat(match-events): is typing

src/components/bot-buster-logo/botbuster-logo-animation.tsx, src/components/bot-buster-logo/styles.ts, src/components/landing-page-animation/landing-page-animation.tsx, src/components/landing-page-animation/styles.ts, src/components/top-ranked/styles.ts, src/components/top-ranked/top-ranked.tsx, src/pages/index.tsx, src/styles/pages/homepage.ts
This PR updates the animations for the homepage
- Improved animated svg rendering to be scalable for large screens
=> feat: updated homepage and animations for large screens

src/assets/text/achievements.ts, src/assets/text/player-profile.ts, src/components/tables/achievements-table.tsx, src/components/tables/components/header/header.tsx, src/components/tables/components/header/styles.ts, src/pages/player-profile.tsx
Added achievements table to the player profile
=> feat: Added achievements to player profile

src/assets/text/match-prompts.ts, src/constants/main.ts, src/server/service/agent/agent.ts, src/utils/messages.ts
* Upgrade RegEx to clean up messages
* Update System Prompt
* Upgrade splitMessage logic for better consistency
* Remove bad host prompt
* Increase max characters in message to 160
=> fix(agent): message cleanup

src/server/service/agent/agent.ts
* Add profanity filter to agent messages
=> fix(agent): profanity filter

src/components/character-typing/character-typing-indicator.tsx, src/components/character-typing/index.ts, src/components/character-typing/styles.ts, src/components/chat/chat.tsx, src/components/chat/styles.ts, src/components/primary-button/primary-button.tsx
This PR introduces the "is typing feature" so that players can see who is typing during the chat stage of the match
- Added top grey banner to display which characters are typing
- Added "..." animation
=> Feat: is Typing ... Indicator

deployment/staging/deployment.yaml
=> fix(match): increase total players

src/pages/player-profile.tsx, src/server/api/routers/user.ts
* Add getUserAchievements query to DB API
=> feat(db): users achievements query

src/components/bullet-point/bullet-point.tsx, src/components/player-profiles/player-profiles.tsx, src/components/points-and-penalties/points-and-penalties.tsx
fixed bug in penalities and points component. The component is no longer an array.
=> fixed bug issue.

src/server/service/agent/agent.ts
* Upgrade typing time calculation
* Fix initial seed for requests
* Update system prompt for agents to give shorter replies
=> fix(agent): similar replies

src/server/service/agent/agent.ts, src/utils/messages.ts
* Add extra message filter for common sentences
* Update SYS prompt for more consistent bad grammar
* Add extra reading time before first message
=> fix(agent): common replies

deployment/staging/deployment.yaml, infra/inference-lambda.py, infra/infererence-lambda-bedrock.py, src/server/service/agent/agent.ts
* Update inference URL
* Add Lambda for new inference endpoint for on-demand inference
=> feat(agent): inference upgrade

infra/infererence-lambda-bedrock.py, src/constants/index.ts, src/constants/models.ts, src/server/service/agent/agent.ts, src/types/agent.ts
* Add multiple models to select for invoking inference
* Add lambda function used to invoke bedrock inference
=> feat(agent): model endpoint selection

src/constants/models.ts
* Remove Llama 2 13B
* Remove Llama 2 70B
=> fix(agent): Remove llama 2 models from agent list
